<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_System_CENTER_button_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e</name>
   <tag></tag>
   <elementGuidId>ffff3f59-27c7-4c50-b90b-25a80b68513a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CENTER_button_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CENTER_button_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>more actions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>post__dropdown color--link style--none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>dotmenu-icon-tooltip</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CENTER_button_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CENTER_button_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post_user-activity-86ujaoaqgf8wfbswktec6hfy5e_j5njbrcqmtdsmmk4yrks3zsu4a_oxuhn56r83yb98pffaaboackha_d1cc5gyym38kmc7f5zbmj3k35e']/div/div[2]/div/div[2]/div/div[2]/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div[2]/div/div[2]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
